import 'package:copy_with_extension/copy_with_extension.dart';
import 'package:json_annotation/json_annotation.dart';

part 'subscription_event.g.dart';

/// Represents an event in the subscription lifecycle.
///
/// This model stores all events related to subscriptions for audit and debugging purposes.
/// Events are typically generated by RevenueCat webhooks.
@JsonSerializable(fieldRename: FieldRename.snake)
@CopyWith()
class SubscriptionEvent {
  /// Creates an instance of [SubscriptionEvent].
  const SubscriptionEvent({
    required this.id,
    this.subscriptionId,
    required this.userId,
    required this.eventType,
    this.vendorEventId,
    required this.eventTime,
    required this.eventPayload,
    required this.createdAt,
  });

  /// Creates a [SubscriptionEvent] from a JSON object.
  factory SubscriptionEvent.fromJson(Map<String, dynamic> json) =>
      _$SubscriptionEventFromJson(json);

  /// The unique identifier for the event.
  final String id;

  /// The ID of the subscription this event is related to.
  /// Can be null if the event occurs before subscription creation.
  @JsonKey(name: 'subscription_id')
  final String? subscriptionId;

  /// The ID of the user this event is related to.
  @JsonKey(name: 'user_id')
  final String userId;

  /// The type of event (e.g., 'INITIAL_PURCHASE', 'RENEWAL', 'CANCELLATION').
  @JsonKey(name: 'event_type')
  final String eventType;

  /// The unique identifier for this event from the vendor (RevenueCat).
  /// Used for idempotence.
  @JsonKey(name: 'vendor_event_id')
  final String? vendorEventId;

  /// The timestamp when the event occurred.
  @JsonKey(name: 'event_time')
  final DateTime eventTime;

  /// The full payload of the event as received from the vendor.
  @JsonKey(name: 'event_payload')
  final Map<String, dynamic> eventPayload;

  /// The timestamp when this event record was created in the database.
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  /// Converts this [SubscriptionEvent] to a JSON object.
  Map<String, dynamic> toJson() => _$SubscriptionEventToJson(this);
}
