import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:trainer_backend/clients/trainer.api.dart';
import 'package:trainer_backend/models/subscriptions/customer_info.dart';
import 'package:trainer_backend/models/subscriptions/entitlement_info.dart';
import 'package:trainer_backend/models/subscriptions/enums/subscription_status.dart';
import 'package:trainer_backend/models/subscriptions/package.dart';
import 'package:trainer_backend/models/subscriptions/product_summary.dart';
import 'package:trainer_backend/models/subscriptions/subscription_summary.dart';

/// Builder class for constructing [SubscriptionSummary] objects.
///
/// This class provides static methods to:
/// - Fetch entitlement limits from Supabase by entitlement key
/// - Build a complete [SubscriptionSummary] from RevenueCat [CustomerInfo]
///
/// This is useful for immediate post-purchase feedback without waiting
/// for the RevenueCat webhook to be processed.
class SubscriptionSummaryUtils {
  /// Private constructor to prevent instantiation.
  const SubscriptionSummaryUtils._();

  /// A private getter for the Supabase client instance.
  static SupabaseClient get _client => TrainerAPI.client;

  /// Fetches entitlement limits from Supabase by entitlement key.
  ///
  /// This method calls the `get_entitlement_limits_by_key` RPC function
  /// to retrieve subscription limits directly by entitlement key,
  /// without needing a subscription record.
  ///
  /// - [entitlementKey]: The entitlement key (e.g., "Premium", "Basic").
  ///
  /// Returns a [SubscriptionSummaryLimits] with the limits for the entitlement.
  /// Returns default limits if the entitlement is not found.
  /// Throws a [PostgrestException] if the RPC call fails.
  static Future<SubscriptionSummaryLimits> getEntitlementLimits(
    String entitlementKey,
  ) async {
    final dynamic response = await _client.rpc(
      'get_entitlement_limits_by_key',
      params: <String, dynamic>{'p_entitlement_key': entitlementKey},
    );

    if (response == null) {
      return const SubscriptionSummaryLimits();
    }

    return SubscriptionSummaryLimits.fromJson(response as Map<String, dynamic>);
  }

  /// Builds a [SubscriptionSummary] from RevenueCat [CustomerInfo], limits, and package info.
  ///
  /// This method constructs a complete [SubscriptionSummary] that can be used
  /// for immediate UI updates after a purchase, without waiting for the webhook.
  ///
  /// - [customerInfo]: The [CustomerInfo] returned from RevenueCat after purchase.
  /// - [limits]: The [SubscriptionSummaryLimits] fetched via [getEntitlementLimits].
  /// - [package]: The [Package] that was purchased.
  /// - [entitlementKey]: The entitlement key (e.g., "Premium", "Basic").
  ///
  /// Returns a [SubscriptionSummary] with all available information.
  /// Note: The `id` and `entitlement.id` fields will be empty strings as they
  /// are generated by Supabase when the webhook creates the subscription record.
  ///
  /// Throws an [Exception] if the entitlement is not found in [customerInfo].
  static SubscriptionSummary buildFromCustomerInfo({
    required CustomerInfo customerInfo,
    required SubscriptionSummaryLimits limits,
    required Package package,
    required String entitlementKey,
  }) {
    final EntitlementInfo? entitlementInfo = customerInfo.entitlements[entitlementKey];

    if (entitlementInfo == null) {
      throw Exception(
        'Entitlement "$entitlementKey" not found in CustomerInfo after purchase. '
        'Available entitlements: ${customerInfo.entitlements.keys.toList()}',
      );
    }

    return SubscriptionSummary(
      // Empty string as UUID is generated by Supabase webhook
      id: '',
      userId: customerInfo.originalAppUserId,
      status: _mapPeriodTypeToStatus(
        periodType: entitlementInfo.periodType,
        isActive: entitlementInfo.isActive,
      ),
      startedAt: entitlementInfo.originalPurchaseDate,
      expiresAt: entitlementInfo.expirationDate,
      isTrial: _isTrial(entitlementInfo.periodType),
      entitlement: SubscriptionSummaryEntitlement(
        // Empty string as UUID is generated by Supabase webhook
        id: '',
        entitlementKey: entitlementKey,
        name: entitlementKey,
      ),
      product: ProductSummary(
        // Empty string as UUID is generated by Supabase webhook
        id: '',
        productId: entitlementInfo.productIdentifier,
        vendor: _extractVendorFromStore(entitlementInfo.store),
        periodInterval: null,
      ),
      limits: limits,
    );
  }

  /// Maps RevenueCat period type to [SubscriptionStatus].
  ///
  /// - [periodType]: The period type string from RevenueCat (e.g., "PeriodType.trial").
  /// - [isActive]: Whether the entitlement is currently active.
  ///
  /// Returns the corresponding [SubscriptionStatus].
  static SubscriptionStatus _mapPeriodTypeToStatus({
    required String periodType,
    required bool isActive,
  }) {
    if (!isActive) {
      return SubscriptionStatus.expired;
    }

    final String lowerPeriodType = periodType.toLowerCase();

    if (lowerPeriodType.contains('trial')) {
      return SubscriptionStatus.trialing;
    }

    if (lowerPeriodType.contains('intro')) {
      return SubscriptionStatus.active;
    }

    return SubscriptionStatus.active;
  }

  /// Determines if the subscription is in trial period.
  ///
  /// - [periodType]: The period type string from RevenueCat.
  ///
  /// Returns `true` if the period type indicates a trial.
  static bool _isTrial(String periodType) => periodType.toLowerCase().contains('trial');

  /// Extracts a vendor identifier from the RevenueCat store string.
  ///
  /// - [store]: The store string from RevenueCat (e.g., "Store.appStore").
  ///
  /// Returns a normalized vendor string (e.g., "app_store", "play_store", "test_store").
  static String _extractVendorFromStore(String store) {
    final String lowerStore = store.toLowerCase();

    if (lowerStore.contains('appstore') || lowerStore.contains('app_store')) {
      return 'app_store';
    }

    if (lowerStore.contains('playstore') || lowerStore.contains('play_store')) {
      return 'play_store';
    }

    if (lowerStore.contains('amazon')) {
      return 'amazon';
    }

    if (lowerStore.contains('stripe')) {
      return 'stripe';
    }

    // Default for test store or unknown
    return 'test_store';
  }
}
