create type "public"."session_style" as enum ('bodyweight', 'weights', 'stretching_mobility');

create type "public"."session_type" as enum ('CLASSIC', 'EMOM', 'HIIT', 'AMRAP');

create type "public"."user_role" as enum ('standard', 'coach');

create table "public"."exercise_progressions" (
    "user_id" uuid not null,
    "session_exercise_id" bigint not null,
    "next_objective_parameters" jsonb not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "public"."exercise_progressions" enable row level security;

create table "public"."exercises" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "name" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "public"."exercises" enable row level security;

create table "public"."exercises_logs" (
    "id" bigint generated by default as identity not null,
    "round_log_id" bigint not null,
    "session_exercise_id" bigint not null,
    "performance" jsonb not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."exercises_logs" enable row level security;

create table "public"."profiles" (
    "id" uuid not null,
    "role" user_role not null default 'standard'::user_role,
    "full_name" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "username" text not null
);


alter table "public"."profiles" enable row level security;

create table "public"."programs" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "name" text not null,
    "description" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "public"."programs" enable row level security;

create table "public"."round_logs" (
    "id" bigint generated by default as identity not null,
    "session_log_id" bigint not null,
    "round_number" integer not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."round_logs" enable row level security;

create table "public"."session_exercises" (
    "id" bigint generated by default as identity not null,
    "session_id" bigint not null,
    "exercise_id" bigint not null,
    "order_in_session" integer not null,
    "parameters" jsonb not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "public"."session_exercises" enable row level security;

create table "public"."session_logs" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "session_id" bigint not null,
    "started_at" timestamp with time zone not null default now(),
    "ended_at" timestamp with time zone,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."session_logs" enable row level security;

create table "public"."sessions" (
    "id" bigint generated by default as identity not null,
    "program_id" bigint not null,
    "order_in_program" integer not null,
    "type" session_type not null,
    "style" session_style not null,
    "parameters" jsonb,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "name" text not null
);


alter table "public"."sessions" enable row level security;

CREATE UNIQUE INDEX exercise_progressions_pkey ON public.exercise_progressions USING btree (user_id, session_exercise_id);

CREATE UNIQUE INDEX exercises_logs_pkey ON public.exercises_logs USING btree (id);

CREATE UNIQUE INDEX exercises_pkey ON public.exercises USING btree (id);

CREATE UNIQUE INDEX exercises_user_id_name_key ON public.exercises USING btree (user_id, name);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX profiles_username_key ON public.profiles USING btree (username);

CREATE UNIQUE INDEX programs_pkey ON public.programs USING btree (id);

CREATE UNIQUE INDEX round_logs_pkey ON public.round_logs USING btree (id);

CREATE UNIQUE INDEX session_exercises_pkey ON public.session_exercises USING btree (id);

CREATE UNIQUE INDEX session_logs_pkey ON public.session_logs USING btree (id);

CREATE UNIQUE INDEX sessions_pkey ON public.sessions USING btree (id);

CREATE UNIQUE INDEX unique_exercise_per_user ON public.exercises USING btree (user_id, name);

alter table "public"."exercise_progressions" add constraint "exercise_progressions_pkey" PRIMARY KEY using index "exercise_progressions_pkey";

alter table "public"."exercises" add constraint "exercises_pkey" PRIMARY KEY using index "exercises_pkey";

alter table "public"."exercises_logs" add constraint "exercises_logs_pkey" PRIMARY KEY using index "exercises_logs_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."programs" add constraint "programs_pkey" PRIMARY KEY using index "programs_pkey";

alter table "public"."round_logs" add constraint "round_logs_pkey" PRIMARY KEY using index "round_logs_pkey";

alter table "public"."session_exercises" add constraint "session_exercises_pkey" PRIMARY KEY using index "session_exercises_pkey";

alter table "public"."session_logs" add constraint "session_logs_pkey" PRIMARY KEY using index "session_logs_pkey";

alter table "public"."sessions" add constraint "sessions_pkey" PRIMARY KEY using index "sessions_pkey";

alter table "public"."exercise_progressions" add constraint "exercise_progressions_session_exercise_id_fkey" FOREIGN KEY (session_exercise_id) REFERENCES session_exercises(id) ON DELETE CASCADE not valid;

alter table "public"."exercise_progressions" validate constraint "exercise_progressions_session_exercise_id_fkey";

alter table "public"."exercise_progressions" add constraint "exercise_progressions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."exercise_progressions" validate constraint "exercise_progressions_user_id_fkey";

alter table "public"."exercises" add constraint "exercises_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."exercises" validate constraint "exercises_user_id_fkey";

alter table "public"."exercises" add constraint "exercises_user_id_name_key" UNIQUE using index "exercises_user_id_name_key";

alter table "public"."exercises" add constraint "name_validation" CHECK (((char_length(name) >= 2) AND (char_length(name) <= 50))) not valid;

alter table "public"."exercises" validate constraint "name_validation";

alter table "public"."exercises" add constraint "unique_exercise_per_user" UNIQUE using index "unique_exercise_per_user";

alter table "public"."exercises_logs" add constraint "exercises_logs_round_log_id_fkey" FOREIGN KEY (round_log_id) REFERENCES round_logs(id) ON DELETE CASCADE not valid;

alter table "public"."exercises_logs" validate constraint "exercises_logs_round_log_id_fkey";

alter table "public"."exercises_logs" add constraint "exercises_logs_session_exercise_id_fkey" FOREIGN KEY (session_exercise_id) REFERENCES session_exercises(id) ON DELETE SET NULL not valid;

alter table "public"."exercises_logs" validate constraint "exercises_logs_session_exercise_id_fkey";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "profiles_username_key" UNIQUE using index "profiles_username_key";

alter table "public"."profiles" add constraint "username_validation" CHECK (((char_length(username) >= 3) AND (char_length(username) <= 20) AND (username ~ '^[a-z][a-z0-9_]{1,18}[a-z0-9]$'::text))) not valid;

alter table "public"."profiles" validate constraint "username_validation";

alter table "public"."programs" add constraint "description_validation" CHECK ((char_length(COALESCE(description, ''::text)) <= 500)) not valid;

alter table "public"."programs" validate constraint "description_validation";

alter table "public"."programs" add constraint "name_validation" CHECK (((char_length(name) >= 3) AND (char_length(name) <= 80))) not valid;

alter table "public"."programs" validate constraint "name_validation";

alter table "public"."programs" add constraint "programs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."programs" validate constraint "programs_user_id_fkey";

alter table "public"."round_logs" add constraint "round_logs_session_log_id_fkey" FOREIGN KEY (session_log_id) REFERENCES session_logs(id) ON DELETE CASCADE not valid;

alter table "public"."round_logs" validate constraint "round_logs_session_log_id_fkey";

alter table "public"."session_exercises" add constraint "session_exercises_exercise_id_fkey" FOREIGN KEY (exercise_id) REFERENCES exercises(id) ON DELETE CASCADE not valid;

alter table "public"."session_exercises" validate constraint "session_exercises_exercise_id_fkey";

alter table "public"."session_exercises" add constraint "session_exercises_session_id_fkey" FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE not valid;

alter table "public"."session_exercises" validate constraint "session_exercises_session_id_fkey";

alter table "public"."session_logs" add constraint "session_logs_session_id_fkey" FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE SET NULL not valid;

alter table "public"."session_logs" validate constraint "session_logs_session_id_fkey";

alter table "public"."session_logs" add constraint "session_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."session_logs" validate constraint "session_logs_user_id_fkey";

alter table "public"."sessions" add constraint "sessions_program_id_fkey" FOREIGN KEY (program_id) REFERENCES programs(id) ON DELETE CASCADE not valid;

alter table "public"."sessions" validate constraint "sessions_program_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.add_session_to_program(p_program_id integer, session_data jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    new_session_id INT;
    exercise_data jsonb;
    new_exercise_id INT;
    new_session_exercise_id INT;
    new_order_in_program INT;
    v_user_id UUID := auth.uid();
BEGIN
    -- Verify ownership of the program
    IF NOT EXISTS (
        SELECT 1 FROM programs
        WHERE id = p_program_id AND user_id = v_user_id
    ) THEN
        RAISE EXCEPTION 'Program not found or access denied';
    END IF;

    -- Determine the order for the new session
    SELECT COALESCE(MAX(order_in_program), 0) + 1
    INTO new_order_in_program
    FROM sessions
    WHERE program_id = p_program_id;

    -- Insert the session
    INSERT INTO sessions (program_id, name, order_in_program, type, style, parameters)
    VALUES (
        p_program_id,
        session_data->>'name',
        new_order_in_program,
        (session_data->>'type')::session_type,
        (session_data->>'style')::session_style,
        CASE
            WHEN (session_data->>'type')::session_type = 'AMRAP' THEN
                jsonb_build_object('duration', (session_data->>'duration')::bigint)
            WHEN (session_data->>'type')::session_type IN ('EMOM', 'HIIT') THEN
                jsonb_build_object('round_number', (session_data->>'round_number')::int)
            ELSE '{}'::jsonb
        END
    )
    RETURNING id INTO new_session_id;

    -- Loop through exercises for the new session
    FOR exercise_data IN SELECT * FROM jsonb_array_elements(session_data->'exercises')
    LOOP
        -- Find or create the exercise for the current user
        INSERT INTO exercises (user_id, name)
        VALUES (v_user_id, exercise_data->>'name')
        ON CONFLICT (user_id, name) DO NOTHING;

        SELECT id INTO new_exercise_id FROM exercises WHERE user_id = v_user_id AND name = exercise_data->>'name';

        -- Insert into session_exercises using the correct key 'parameters'
        INSERT INTO session_exercises (session_id, exercise_id, order_in_session, parameters)
        VALUES (
            new_session_id,
            new_exercise_id,
            (exercise_data->>'order_in_session')::INT,
            (exercise_data->'parameters')::jsonb
        )
        RETURNING id INTO new_session_exercise_id;

        -- Create initial progression record using the correct keys
        INSERT INTO exercise_progressions (user_id, session_exercise_id, next_objective_parameters)
        VALUES (
            v_user_id,
            new_session_exercise_id,
            COALESCE(
                (exercise_data->'progression'->0->'next_objective_parameters')::jsonb,
                (exercise_data->'parameters')::jsonb
            )
        );
    END LOOP;

    -- Return the complete program data using the same logic as other functions
    RETURN (
        SELECT get_full_program_by_id(p_program_id)
    );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.create_full_program(full_program_data jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    new_program_id INT;
    session_data jsonb;
    new_session_id INT;
    exercise_data jsonb;
    new_exercise_id INT;
    new_session_exercise_id INT;
    v_user_id UUID := auth.uid();
BEGIN
    -- Insert the program
    INSERT INTO programs (user_id, name, description)
    VALUES (
        v_user_id,
        full_program_data->>'name',
        full_program_data->>'description'
    )
    RETURNING id INTO new_program_id;

    -- Loop through sessions
    FOR session_data IN SELECT * FROM jsonb_array_elements(full_program_data->'sessions')
    LOOP
        -- Insert the session
        INSERT INTO sessions (program_id, name, "order_in_program", type, style, parameters)
        VALUES (
            new_program_id,
            session_data->>'name',
            (session_data->>'order_in_program')::INT,
            (session_data->>'type')::session_type,
            (session_data->>'style')::session_style,
            CASE
                WHEN (session_data->>'type')::session_type = 'AMRAP' THEN
                    jsonb_build_object('duration', (session_data->>'duration')::bigint)
                WHEN (session_data->>'type')::session_type IN ('EMOM', 'HIIT') THEN
                    jsonb_build_object('round_number', (session_data->>'round_number')::int)
                ELSE
                    '{}'::jsonb
            END
        )
        RETURNING id INTO new_session_id;

        -- Loop through exercises
        FOR exercise_data IN SELECT * FROM jsonb_array_elements(session_data->'exercises')
        LOOP
            -- Find or create the exercise FOR THE CURRENT USER
            INSERT INTO exercises (user_id, name)
            VALUES (v_user_id, exercise_data->>'name')
            ON CONFLICT (user_id, name) DO NOTHING;

            SELECT id INTO new_exercise_id FROM exercises WHERE user_id = v_user_id AND name = exercise_data->>'name';

            -- Insert into session_exercises
            INSERT INTO session_exercises (session_id, exercise_id, "order_in_session", parameters)
            VALUES (
                new_session_id,
                new_exercise_id,
                (exercise_data->>'order_in_session')::INT,
                (exercise_data->'parameters')::jsonb
            )
            RETURNING id INTO new_session_exercise_id;

            -- Always create an initial progression record, now including the user_id
            INSERT INTO exercise_progressions (user_id, session_exercise_id, next_objective_parameters)
            VALUES (
                v_user_id,
                new_session_exercise_id,
                COALESCE(
                    (exercise_data->'progression'->0->'next_objective_parameters')::jsonb,
                    (exercise_data->'parameters')::jsonb
                )
            );
        END LOOP;
    END LOOP;

    -- Return the complete program data
    RETURN (
        SELECT get_full_program_by_id(new_program_id)
    );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.create_session_log(session_log_data jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    new_session_log_id INT;
    round_data jsonb;
    new_round_log_id INT;
    exercise_log_data jsonb;
    v_user_id UUID := auth.uid();
    v_session_id INT;
    v_created_log jsonb;
BEGIN
    v_session_id := (session_log_data->>'session_id')::int;

    -- Verify that the user owns the original session
    IF NOT EXISTS (
        SELECT 1
        FROM public.sessions s
        JOIN public.programs p ON s.program_id = p.id
        WHERE s.id = v_session_id AND p.user_id = v_user_id
    ) THEN
        RAISE EXCEPTION 'Session not found or access denied';
    END IF;

    -- Insert the main session log
    INSERT INTO public.session_logs (user_id, session_id, started_at, ended_at)
    VALUES (
        v_user_id,
        v_session_id,
        (session_log_data->>'started_at')::timestamptz,
        (session_log_data->>'ended_at')::timestamptz
    )
    RETURNING id INTO new_session_log_id;

    -- Loop through rounds
    FOR round_data IN SELECT * FROM jsonb_array_elements(session_log_data->'rounds')
    LOOP
        -- Insert the round log
        INSERT INTO public.round_logs (session_log_id, round_number)
        VALUES (
            new_session_log_id,
            (round_data->>'round_number')::int
        )
        RETURNING id INTO new_round_log_id;

        -- Loop through exercise logs in the round
        FOR exercise_log_data IN SELECT * FROM jsonb_array_elements(round_data->'exercises')
        LOOP
            -- Insert the exercise log
            INSERT INTO public.exercises_logs (round_log_id, session_exercise_id, performance)
            VALUES (
                new_round_log_id,
                (exercise_log_data->>'session_exercise_id')::int,
                exercise_log_data
            );
        END LOOP;
    END LOOP;

    -- Fetch and build the complete SessionLog object to return
    SELECT
        jsonb_build_object(
            'id', sl.id,
            'session_id', sl.session_id,
            'started_at', sl.started_at,
            'ended_at', sl.ended_at,
            'type', s.type, -- For SessionLog deserialization
            'rounds', COALESCE((
                SELECT jsonb_agg(
                    jsonb_build_object(
                        'id', rl.id,
                        'round_number', rl.round_number,
                        'exercises', COALESCE((
                            SELECT jsonb_agg(
                                -- The 'performance' object from the table is the ExerciseLog itself
                                el.performance || jsonb_build_object('type', s.type)
                            )
                            FROM public.exercises_logs el
                            WHERE el.round_log_id = rl.id
                        ), '[]'::jsonb)
                    ) ORDER BY rl.round_number
                )
                FROM public.round_logs rl
                WHERE rl.session_log_id = sl.id
            ), '[]'::jsonb)
        )
    INTO v_created_log
    FROM public.session_logs sl
    JOIN public.sessions s ON sl.session_id = s.id
    WHERE sl.id = new_session_log_id;

    -- Return the created log directly for consistency
    RETURN v_created_log;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.delete_program(p_program_id integer)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    deleted_id INT;
BEGIN
    DELETE FROM programs
    WHERE id = p_program_id AND user_id = auth.uid()
    RETURNING id INTO deleted_id;

    IF deleted_id IS NULL THEN
        RAISE EXCEPTION 'Program not found or access denied';
    END IF;

    RETURN deleted_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.delete_session_from_program(p_session_id integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_program_id INT;
    v_user_id UUID := auth.uid();
    session_count INT;
BEGIN
    -- Find the program_id for the session to be deleted and verify ownership
    SELECT program_id INTO v_program_id
    FROM sessions s
    JOIN programs p ON s.program_id = p.id
    WHERE s.id = p_session_id AND p.user_id = v_user_id;

    IF v_program_id IS NULL THEN
        RAISE EXCEPTION 'Session not found or access denied';
    END IF;

    -- Check if it's the last session in the program
    SELECT COUNT(*) INTO session_count
    FROM sessions
    WHERE program_id = v_program_id;

    IF session_count <= 1 THEN
        RAISE EXCEPTION 'Cannot delete the last session of a program.';
    END IF;

    -- Delete the session (cascades to session_exercises and exercise_progressions)
    DELETE FROM sessions WHERE id = p_session_id;

    -- Re-order the remaining sessions
    WITH ranked_sessions AS (
        SELECT
            id,
            ROW_NUMBER() OVER (ORDER BY order_in_program) as new_order
        FROM sessions
        WHERE program_id = v_program_id
    )
    UPDATE sessions s
    SET order_in_program = rs.new_order
    FROM ranked_sessions rs
    WHERE s.id = rs.id;

    -- Return the complete updated program data
    RETURN (
       SELECT get_full_program_by_id(v_program_id)
    );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.delete_user_account()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  -- First, delete the user's profile from the public.profiles table
  delete from public.profiles where id = auth.uid();
  
  -- Then, delete the user from the auth.users table
  delete from auth.users where id = auth.uid();
end;
$function$
;

CREATE OR REPLACE FUNCTION public.get_full_session_by_id(p_session_id integer)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
AS $function$
SELECT
    jsonb_strip_nulls(
        jsonb_build_object(
            'id', s.id,
            'program_id', s.program_id,
            'order_in_program', s.order_in_program,
            'name', s.name,
            'session_type', s.type,
            'session_style', s.style,
            'parameters', s.parameters,
            'exercises', COALESCE(
                (
                    SELECT
                        jsonb_agg(
                            jsonb_build_object(
                                'id', se.id,
                                'exercise_id', se.exercise_id,
                                'name', e.name,
                                'order_in_session', se.order_in_session,
                                'template_parameters', se.parameters->'template',
                                'objective_parameters', se.parameters->'objective'
                            ) ORDER BY se.order_in_session
                        )
                    FROM public.session_exercises se
                    JOIN public.exercises e ON se.exercise_id = e.id
                    WHERE se.session_id = s.id
                ),
                '[]'::jsonb
            )
        )
    )
FROM
    public.sessions s
WHERE
    s.id = p_session_id;
$function$
;

CREATE OR REPLACE FUNCTION public.get_user_programs(page_number integer, page_size integer)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_user_id UUID := auth.uid();
BEGIN
    RETURN (
        SELECT jsonb_agg(program_json)
        FROM (
            SELECT jsonb_build_object(
                'id', p.id,
                'user_id', p.user_id,
                'name', p.name,
                'description', p.description,
                'created_at', p.created_at,
                'updated_at', p.updated_at,
                'is_favorite', EXISTS (
                    SELECT 1
                    FROM favorite_programs fp
                    WHERE fp.program_id = p.id AND fp.user_id = v_user_id
                ),
                'sessions', (
                    SELECT jsonb_agg(
                        jsonb_build_object(
                            'id', s.id,
                            'name', s.name,
                            'order_in_program', s.order_in_program,
                            'type', s.type,
                            'style', s.style,
                            'exercises', (
                                SELECT jsonb_agg(
                                    jsonb_build_object(
                                        'id', se.id,
                                        'exercise_id', se.exercise_id,
                                        'order_in_session', se.order_in_session,
                                        'exercise', jsonb_build_object('name', e.name),
                                        'parameters', se.parameters,
                                        'progression', (
                                            SELECT jsonb_agg(ep.*)
                                            FROM exercise_progressions ep
                                            WHERE ep.session_exercise_id = se.id
                                        )
                                    )
                                )
                                FROM session_exercises se
                                JOIN exercises e ON se.exercise_id = e.id
                                WHERE se.session_id = s.id
                            )
                        )
                        ||
                        CASE
                            WHEN s.type = 'AMRAP' THEN
                                jsonb_build_object('duration', s.parameters->'duration')
                            WHEN s.type IN ('EMOM', 'HIIT') THEN
                                jsonb_build_object('round_number', s.parameters->'round_number')
                            ELSE
                                '{}'::jsonb
                        END
                    )
                    FROM sessions s
                    WHERE s.program_id = p.id
                )
            ) as program_json
            FROM programs p
            WHERE p.user_id = v_user_id
            ORDER BY p.created_at DESC
            LIMIT page_size
            OFFSET page_number * page_size
        ) as paginated_programs
    );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_user_sessions_logs(page_number integer, page_size integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_user_id UUID := auth.uid();
BEGIN
    RETURN (
        SELECT jsonb_agg(log_json)
        FROM (
            SELECT
                jsonb_build_object(
                    'id', sl.id,
                    'session_id', sl.session_id,
                    'started_at', sl.started_at,
                    'ended_at', sl.ended_at,
                    'type', s.type, -- Crucial for deserialization
                    'rounds', COALESCE((
                        SELECT jsonb_agg(
                            jsonb_build_object(
                                'id', rl.id,
                                'round_number', rl.round_number,
                                'exercises', COALESCE((
                                    SELECT jsonb_agg(
                                        -- Inject session type and exercise name for full deserialization
                                        el.performance || jsonb_build_object(
                                            'type', s.type,
                                            'exercise_name', (
                                                SELECT ex.name
                                                FROM public.session_exercises se
                                                JOIN public.exercises ex ON se.exercise_id = ex.id
                                                WHERE se.id = el.session_exercise_id
                                            )
                                        )
                                    )
                                    FROM public.exercises_logs el
                                    WHERE el.round_log_id = rl.id
                                ), '[]'::jsonb)
                            ) ORDER BY rl.round_number
                        )
                        FROM public.round_logs rl
                        WHERE rl.session_log_id = sl.id
                    ), '[]'::jsonb)
                ) as log_json
            FROM public.session_logs sl
            JOIN public.sessions s ON sl.session_id = s.id
            JOIN public.programs p ON s.program_id = p.id
            WHERE p.user_id = v_user_id
            ORDER BY sl.started_at DESC
            LIMIT page_size
            OFFSET page_number * page_size
        ) as paginated_logs
    );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.profiles (id, full_name, username, role)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'username', 'standard');
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.update_full_program(full_program_data jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    program_id_to_update int;
    session_data jsonb;
    v_user_id UUID := auth.uid();
BEGIN
    -- 1. Extract program ID and verify ownership
    program_id_to_update := (full_program_data->>'id')::int;
    IF NOT EXISTS (
        SELECT 1 FROM programs
        WHERE id = program_id_to_update AND user_id = v_user_id
    ) THEN
        RAISE EXCEPTION 'Program not found or access denied';
    END IF;

    -- 2. Update program metadata
    UPDATE programs
    SET
        name = full_program_data->>'name',
        description = full_program_data->>'description'
    WHERE id = program_id_to_update;

    -- 3. Loop through sessions from input and update their order
    FOR session_data IN SELECT * FROM jsonb_array_elements(full_program_data->'sessions')
    LOOP
        UPDATE sessions
        SET order_in_program = (session_data->>'order_in_program')::int
        WHERE id = (session_data->>'id')::int AND program_id = program_id_to_update;
    END LOOP;

    -- 4. Return the complete program data, using the EXACT same return logic as the other RPCs.
    RETURN (
        SELECT get_full_program_by_id(program_id_to_update)
    );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_full_session(p_session_data jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_session_id INT;
    v_auth_user_id UUID := auth.uid();
    v_program_id INT;
    exercise_data jsonb;
    v_session_exercise_id INT;
    v_exercise_id INT;
    v_exercise_name TEXT;
    v_existing_exercise_ids INT[];
    v_ids_to_keep INT[] := '{}'::int[];
BEGIN
    -- Extract session ID and verify ownership, get program_id
    v_session_id := (p_session_data->>'id')::int;
    IF v_session_id IS NULL THEN
        RAISE EXCEPTION 'Session ID is missing from the payload.';
    END IF;

    SELECT s.program_id INTO v_program_id
    FROM public.sessions s
    JOIN public.programs p ON s.program_id = p.id
    WHERE s.id = v_session_id AND p.user_id = v_auth_user_id;

    IF v_program_id IS NULL THEN
        RAISE EXCEPTION 'Session not found or access denied.';
    END IF;

    -- NEW: Validate that the session is not empty
    IF jsonb_array_length(p_session_data->'exercises') = 0 THEN
        RAISE EXCEPTION 'A session must contain at least one exercise.';
    END IF;

    -- Update session name and parameters
    UPDATE public.sessions
    SET
        name = p_session_data->>'name',
        parameters = CASE
            WHEN (p_session_data->>'type')::session_type = 'AMRAP' THEN jsonb_build_object('duration', (p_session_data->>'duration')::bigint)
            WHEN (p_session_data->>'type')::session_type IN ('EMOM', 'HIIT') THEN jsonb_build_object('round_number', (p_session_data->>'round_number')::int)
            ELSE '{}'::jsonb
        END
    WHERE id = v_session_id;

    -- Get current exercise IDs for deletion tracking
    SELECT array_agg(id) INTO v_existing_exercise_ids
    FROM public.session_exercises
    WHERE session_id = v_session_id;

    -- Loop through input exercises for UPSERT and reordering
    FOR exercise_data IN SELECT * FROM jsonb_array_elements(p_session_data->'exercises')
    LOOP
        IF exercise_data->'parameters' IS NULL THEN
            RAISE EXCEPTION 'Exercise "%" is missing required "parameters".', exercise_data->>'name';
        END IF;

        v_exercise_name := exercise_data->>'name';
        SELECT id INTO v_exercise_id
        FROM public.exercises
        WHERE user_id = v_auth_user_id AND name = v_exercise_name;

        IF v_exercise_id IS NULL THEN
            INSERT INTO public.exercises (user_id, name)
            VALUES (v_auth_user_id, v_exercise_name)
            RETURNING id INTO v_exercise_id;
        END IF;

        v_session_exercise_id := (exercise_data->>'id')::int;

        IF v_session_exercise_id IS NULL OR v_session_exercise_id = 0 THEN
            INSERT INTO public.session_exercises (session_id, exercise_id, order_in_session, parameters)
            VALUES (v_session_id, v_exercise_id, (exercise_data->>'order_in_session')::int, (exercise_data->'parameters')::jsonb)
            RETURNING id INTO v_session_exercise_id;

            INSERT INTO public.exercise_progressions (user_id, session_exercise_id, next_objective_parameters)
            VALUES (v_auth_user_id, v_session_exercise_id, COALESCE((exercise_data->'progression'->0->'next_objective_parameters')::jsonb, (exercise_data->'parameters')::jsonb));
        ELSE
            UPDATE public.session_exercises
            SET order_in_session = (exercise_data->>'order_in_session')::int,
                parameters = (exercise_data->'parameters')::jsonb
            WHERE id = v_session_exercise_id AND session_id = v_session_id;

            UPDATE public.exercise_progressions
            SET next_objective_parameters = COALESCE((exercise_data->'progression'->0->'next_objective_parameters')::jsonb, (exercise_data->'parameters')::jsonb)
            WHERE session_exercise_id = v_session_exercise_id;
        END IF;

        v_ids_to_keep := array_append(v_ids_to_keep, v_session_exercise_id);
    END LOOP;

    -- Delete removed exercises
    DELETE FROM public.session_exercises
    WHERE session_id = v_session_id AND id = ANY(COALESCE(v_existing_exercise_ids, '{}'::int[])) AND id NOT IN (SELECT unnest(v_ids_to_keep));

    -- Return response matching SessionApiResponse (program_id and session)
    RETURN jsonb_build_object(
        'program_id', v_program_id,
        'session', (
            SELECT jsonb_build_object(
                'id', s.id,
                'name', s.name,
                'order_in_program', s.order_in_program,
                'type', s.type,
                'style', s.style,
                'exercises', (
                    SELECT jsonb_agg(
                        jsonb_build_object(
                            'id', se.id,
                            'exercise_id', se.exercise_id,
                            'order_in_session', se.order_in_session,
                            'exercise', jsonb_build_object('name', e.name), -- FIX for deserialization
                            'parameters', se.parameters,
                            'progression', (
                                SELECT jsonb_agg(ep.*)
                                FROM public.exercise_progressions ep
                                WHERE ep.session_exercise_id = se.id
                            )
                        ) ORDER BY se.order_in_session
                    )
                    FROM public.session_exercises se
                    JOIN public.exercises e ON se.exercise_id = e.id
                    WHERE se.session_id = s.id
                )
            ) ||
            CASE
                WHEN s.type = 'AMRAP' THEN jsonb_build_object('duration', s.parameters->'duration')
                WHEN s.type IN ('EMOM', 'HIIT') THEN jsonb_build_object('round_number', s.parameters->'round_number')
                ELSE '{}'::jsonb
            END
            FROM public.sessions s
            WHERE s.id = v_session_id
        )
    );
END;
$function$
;

grant delete on table "public"."exercise_progressions" to "anon";

grant insert on table "public"."exercise_progressions" to "anon";

grant references on table "public"."exercise_progressions" to "anon";

grant select on table "public"."exercise_progressions" to "anon";

grant trigger on table "public"."exercise_progressions" to "anon";

grant truncate on table "public"."exercise_progressions" to "anon";

grant update on table "public"."exercise_progressions" to "anon";

grant delete on table "public"."exercise_progressions" to "authenticated";

grant insert on table "public"."exercise_progressions" to "authenticated";

grant references on table "public"."exercise_progressions" to "authenticated";

grant select on table "public"."exercise_progressions" to "authenticated";

grant trigger on table "public"."exercise_progressions" to "authenticated";

grant truncate on table "public"."exercise_progressions" to "authenticated";

grant update on table "public"."exercise_progressions" to "authenticated";

grant delete on table "public"."exercise_progressions" to "service_role";

grant insert on table "public"."exercise_progressions" to "service_role";

grant references on table "public"."exercise_progressions" to "service_role";

grant select on table "public"."exercise_progressions" to "service_role";

grant trigger on table "public"."exercise_progressions" to "service_role";

grant truncate on table "public"."exercise_progressions" to "service_role";

grant update on table "public"."exercise_progressions" to "service_role";

grant delete on table "public"."exercises" to "anon";

grant insert on table "public"."exercises" to "anon";

grant references on table "public"."exercises" to "anon";

grant select on table "public"."exercises" to "anon";

grant trigger on table "public"."exercises" to "anon";

grant truncate on table "public"."exercises" to "anon";

grant update on table "public"."exercises" to "anon";

grant delete on table "public"."exercises" to "authenticated";

grant insert on table "public"."exercises" to "authenticated";

grant references on table "public"."exercises" to "authenticated";

grant select on table "public"."exercises" to "authenticated";

grant trigger on table "public"."exercises" to "authenticated";

grant truncate on table "public"."exercises" to "authenticated";

grant update on table "public"."exercises" to "authenticated";

grant delete on table "public"."exercises" to "service_role";

grant insert on table "public"."exercises" to "service_role";

grant references on table "public"."exercises" to "service_role";

grant select on table "public"."exercises" to "service_role";

grant trigger on table "public"."exercises" to "service_role";

grant truncate on table "public"."exercises" to "service_role";

grant update on table "public"."exercises" to "service_role";

grant delete on table "public"."exercises_logs" to "anon";

grant insert on table "public"."exercises_logs" to "anon";

grant references on table "public"."exercises_logs" to "anon";

grant select on table "public"."exercises_logs" to "anon";

grant trigger on table "public"."exercises_logs" to "anon";

grant truncate on table "public"."exercises_logs" to "anon";

grant update on table "public"."exercises_logs" to "anon";

grant delete on table "public"."exercises_logs" to "authenticated";

grant insert on table "public"."exercises_logs" to "authenticated";

grant references on table "public"."exercises_logs" to "authenticated";

grant select on table "public"."exercises_logs" to "authenticated";

grant trigger on table "public"."exercises_logs" to "authenticated";

grant truncate on table "public"."exercises_logs" to "authenticated";

grant update on table "public"."exercises_logs" to "authenticated";

grant delete on table "public"."exercises_logs" to "service_role";

grant insert on table "public"."exercises_logs" to "service_role";

grant references on table "public"."exercises_logs" to "service_role";

grant select on table "public"."exercises_logs" to "service_role";

grant trigger on table "public"."exercises_logs" to "service_role";

grant truncate on table "public"."exercises_logs" to "service_role";

grant update on table "public"."exercises_logs" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."programs" to "anon";

grant insert on table "public"."programs" to "anon";

grant references on table "public"."programs" to "anon";

grant select on table "public"."programs" to "anon";

grant trigger on table "public"."programs" to "anon";

grant truncate on table "public"."programs" to "anon";

grant update on table "public"."programs" to "anon";

grant delete on table "public"."programs" to "authenticated";

grant insert on table "public"."programs" to "authenticated";

grant references on table "public"."programs" to "authenticated";

grant select on table "public"."programs" to "authenticated";

grant trigger on table "public"."programs" to "authenticated";

grant truncate on table "public"."programs" to "authenticated";

grant update on table "public"."programs" to "authenticated";

grant delete on table "public"."programs" to "service_role";

grant insert on table "public"."programs" to "service_role";

grant references on table "public"."programs" to "service_role";

grant select on table "public"."programs" to "service_role";

grant trigger on table "public"."programs" to "service_role";

grant truncate on table "public"."programs" to "service_role";

grant update on table "public"."programs" to "service_role";

grant delete on table "public"."round_logs" to "anon";

grant insert on table "public"."round_logs" to "anon";

grant references on table "public"."round_logs" to "anon";

grant select on table "public"."round_logs" to "anon";

grant trigger on table "public"."round_logs" to "anon";

grant truncate on table "public"."round_logs" to "anon";

grant update on table "public"."round_logs" to "anon";

grant delete on table "public"."round_logs" to "authenticated";

grant insert on table "public"."round_logs" to "authenticated";

grant references on table "public"."round_logs" to "authenticated";

grant select on table "public"."round_logs" to "authenticated";

grant trigger on table "public"."round_logs" to "authenticated";

grant truncate on table "public"."round_logs" to "authenticated";

grant update on table "public"."round_logs" to "authenticated";

grant delete on table "public"."round_logs" to "service_role";

grant insert on table "public"."round_logs" to "service_role";

grant references on table "public"."round_logs" to "service_role";

grant select on table "public"."round_logs" to "service_role";

grant trigger on table "public"."round_logs" to "service_role";

grant truncate on table "public"."round_logs" to "service_role";

grant update on table "public"."round_logs" to "service_role";

grant delete on table "public"."session_exercises" to "anon";

grant insert on table "public"."session_exercises" to "anon";

grant references on table "public"."session_exercises" to "anon";

grant select on table "public"."session_exercises" to "anon";

grant trigger on table "public"."session_exercises" to "anon";

grant truncate on table "public"."session_exercises" to "anon";

grant update on table "public"."session_exercises" to "anon";

grant delete on table "public"."session_exercises" to "authenticated";

grant insert on table "public"."session_exercises" to "authenticated";

grant references on table "public"."session_exercises" to "authenticated";

grant select on table "public"."session_exercises" to "authenticated";

grant trigger on table "public"."session_exercises" to "authenticated";

grant truncate on table "public"."session_exercises" to "authenticated";

grant update on table "public"."session_exercises" to "authenticated";

grant delete on table "public"."session_exercises" to "service_role";

grant insert on table "public"."session_exercises" to "service_role";

grant references on table "public"."session_exercises" to "service_role";

grant select on table "public"."session_exercises" to "service_role";

grant trigger on table "public"."session_exercises" to "service_role";

grant truncate on table "public"."session_exercises" to "service_role";

grant update on table "public"."session_exercises" to "service_role";

grant delete on table "public"."session_logs" to "anon";

grant insert on table "public"."session_logs" to "anon";

grant references on table "public"."session_logs" to "anon";

grant select on table "public"."session_logs" to "anon";

grant trigger on table "public"."session_logs" to "anon";

grant truncate on table "public"."session_logs" to "anon";

grant update on table "public"."session_logs" to "anon";

grant delete on table "public"."session_logs" to "authenticated";

grant insert on table "public"."session_logs" to "authenticated";

grant references on table "public"."session_logs" to "authenticated";

grant select on table "public"."session_logs" to "authenticated";

grant trigger on table "public"."session_logs" to "authenticated";

grant truncate on table "public"."session_logs" to "authenticated";

grant update on table "public"."session_logs" to "authenticated";

grant delete on table "public"."session_logs" to "service_role";

grant insert on table "public"."session_logs" to "service_role";

grant references on table "public"."session_logs" to "service_role";

grant select on table "public"."session_logs" to "service_role";

grant trigger on table "public"."session_logs" to "service_role";

grant truncate on table "public"."session_logs" to "service_role";

grant update on table "public"."session_logs" to "service_role";

grant delete on table "public"."sessions" to "anon";

grant insert on table "public"."sessions" to "anon";

grant references on table "public"."sessions" to "anon";

grant select on table "public"."sessions" to "anon";

grant trigger on table "public"."sessions" to "anon";

grant truncate on table "public"."sessions" to "anon";

grant update on table "public"."sessions" to "anon";

grant delete on table "public"."sessions" to "authenticated";

grant insert on table "public"."sessions" to "authenticated";

grant references on table "public"."sessions" to "authenticated";

grant select on table "public"."sessions" to "authenticated";

grant trigger on table "public"."sessions" to "authenticated";

grant truncate on table "public"."sessions" to "authenticated";

grant update on table "public"."sessions" to "authenticated";

grant delete on table "public"."sessions" to "service_role";

grant insert on table "public"."sessions" to "service_role";

grant references on table "public"."sessions" to "service_role";

grant select on table "public"."sessions" to "service_role";

grant trigger on table "public"."sessions" to "service_role";

grant truncate on table "public"."sessions" to "service_role";

grant update on table "public"."sessions" to "service_role";

create policy "Users can manage their own exercise progressions."
on "public"."exercise_progressions"
as permissive
for all
to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));


create policy "Users can manage their own custom exercises."
on "public"."exercises"
as permissive
for all
to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));


create policy "Users can manage exercise logs within their own session logs."
on "public"."exercises_logs"
as permissive
for all
to public
using ((auth.uid() = ( SELECT sl.user_id
   FROM (round_logs rl
     JOIN session_logs sl ON ((rl.session_log_id = sl.id)))
  WHERE (rl.id = exercises_logs.round_log_id))))
with check ((auth.uid() = ( SELECT sl.user_id
   FROM (round_logs rl
     JOIN session_logs sl ON ((rl.session_log_id = sl.id)))
  WHERE (rl.id = exercises_logs.round_log_id))));


create policy "Users can update their own profile."
on "public"."profiles"
as permissive
for update
to public
using ((auth.uid() = id))
with check ((auth.uid() = id));


create policy "Users can view their own profile."
on "public"."profiles"
as permissive
for select
to public
using ((auth.uid() = id));


create policy "Users can manage their own programs."
on "public"."programs"
as permissive
for all
to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));


create policy "Users can manage round logs within their own session logs."
on "public"."round_logs"
as permissive
for all
to public
using ((auth.uid() = ( SELECT session_logs.user_id
   FROM session_logs
  WHERE (session_logs.id = round_logs.session_log_id))))
with check ((auth.uid() = ( SELECT session_logs.user_id
   FROM session_logs
  WHERE (session_logs.id = round_logs.session_log_id))));


create policy "Users can manage exercises in their own sessions"
on "public"."session_exercises"
as permissive
for all
to public
using ((EXISTS ( SELECT 1
   FROM (sessions s
     JOIN programs p ON ((s.program_id = p.id)))
  WHERE ((s.id = session_exercises.session_id) AND (p.user_id = auth.uid())))))
with check ((EXISTS ( SELECT 1
   FROM (sessions s
     JOIN programs p ON ((s.program_id = p.id)))
  WHERE ((s.id = session_exercises.session_id) AND (p.user_id = auth.uid())))));


create policy "Users can manage their own session logs."
on "public"."session_logs"
as permissive
for all
to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));


create policy "Users can manage sessions of their own programs"
on "public"."sessions"
as permissive
for all
to public
using ((EXISTS ( SELECT 1
   FROM programs p
  WHERE ((p.id = sessions.program_id) AND (p.user_id = auth.uid())))))
with check ((EXISTS ( SELECT 1
   FROM programs p
  WHERE ((p.id = sessions.program_id) AND (p.user_id = auth.uid())))));



